version: "3"

networks: 
  aspBlog-network: 
    driver: bridge

volumes:
  frh:

services: 

  db:
    image: mysql
    ports: 
      - "3306:3306"
    volumes:
      - frh:/var/lib/mysql
    environment: 
      MYSQL_DATABASE: piranha
      MYSQL_USER: brad
      MYSQL_PASSWORD: mymymySQL_2018
      MYSQL_ROOT_PASSWORD: mymymySQL_2018
    networks:
      - aspBlog-network

  web: 
    image: frh/dotnet
    volumes:
      - C:/Users/brad/dev/freerangehacks/:/app
    depends_on: 
      - db
    ports: 
      - "80:80"
    networks: 
      - aspBlog-network